# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59837507a0b91aad139eca155c43c078a2a5373377de6a5b7056ab413dd4b5fad3e0d5757800dcd8702e47f602ec924376969e659f3ee222f261b1994d9be5c9

test:
  secret_key_base: 2f9cc21fb6e8a0d09a8729d5939b5a278f44193ecfe817e0ef0db243a9113f1fb6d33a35a11da9520c1e96e047b3f8c426e6bed1a4a5f736cd35e1861b2eca4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
